spring.application.name=jpaTutorial

spring.jpa.hibernate.ddl-auto:update/create/validate/create-drop/none 

#the table we have and the entity we are getting, if they both are different then the validate will give an error.
# then we have create-drop as well do we need to create a table as soon as server run and also drop that table as soon as server closes
#Then we have none also which is used if we dont need to change anything when our entity is update so,
# we can use none and the validate in the production, and the create/update and create-drop in development