INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (5000,15,'tecno_1','tecno spark');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (6000,12,'infinix_1','infinix smart');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (7000,10,'lava_1','lava blaze');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (8000,8,'itel_1','itel vision');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (9000,6,'redmi_1','redmi note 13');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (10000,5,'realme_1','realme narzo');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (11000,7,'poco_1','poco m6');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (12000,5,'realme_2','realme 11x');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (13000,3,'samsung_1','samsung m35');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (14000,2,'redmi_2','redmi note 14');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (15000,4,'vivo_1','vivo t3');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (16000,4,'samsung_2','samsung a15');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (17000,8,'redmi_3','redmi turbo');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (18000,5,'poco_2','poco x6');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (19000,4,'iqoo_1','iqoo z9');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (20000,4,'vivo_2','vivo v30');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (21000,3,'motorola_1','moto edge 50');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (22000,5,'samsung_3','samsung f55');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (23000,3,'iqoo_2','iqoo neo 9');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (24000,3,'poco_3','poco f6');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (25000,2,'oneplus_1','oneplus nord ce4');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (26000,3,'nothing_1','nothing phone 2a');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (27000,3,'vivo_3','vivo v40');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (28000,1,'samsung_4','samsung s23 fe');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (29000,2,'motorola_2','moto edge fusion');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (30000,4,'oneplus_2','oneplus nord 4');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (31000,2,'nothing_2','nothing phone 3');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (32000,2,'iqoo_3','iqoo 12');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (33000,2,'poco_4','poco flagship');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (34000,2,'google_1','pixel 8');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (35000,1,'iqoo_4','iqoo flagship');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (36000,2,'google_2','pixel 8a');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (40000,2,'vivo_4','vivo x100');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (45000,2,'oneplus_3','oneplus 12r');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (50000,1,'apple_1','iphone 14');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (55000,1,'apple_2','iphone 15');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (60000,1,'google_3','pixel 9 pro');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (65000,1,'oneplus_4','oneplus 13');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (70000,1,'apple_3','iphone 16');
INSERT INTO test.product_table (price,quantity,sku,title_x) VALUES (80000,1,'samsung_5','samsung s25 ultra');